apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myweb-deploy
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      env: production
  strategy: 
    type: RollingUpdate
  template: 
    metadata: 
      name: myweb-prod
      labels: 
        env: production
    spec: 
      containers: 
      - image: mykgod/httpd-php-server
        name: myweb-con
